terrain:
  width: 512
  height: 512

noise:
  type: "fbm" # fbm | perlin | simplex | billow | ridged
  seed: 42    # iykyk ;)
  scale: 40.0
  height_scale: 35.0

  # not used for perlin and simplex
  octaves: 4
  persistence: 0.5
  lacunarity: 2.0

output:
  mesh_dir: "meshes/"
  mesh_name: "terrain.obj"
